version: '3.8'

services:
  web:
    build: .
    ports:
      - "5001:5001"
    volumes:
      # Mount specific Python files for development
      - ./app.py:/app/app.py
      - ./functions.py:/app/functions.py
      - ./main.py:/app/main.py
      # Mount templates directory
      - ./templates:/app/templates
      # Mount data directory for manga storage on host
      - ./data:/app/data
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - WITH_PROXY=no
      - BATCH_SIZE=5
    restart: unless-stopped
    # Use Flask development server with hot reload
    command: flask run --host=0.0.0.0 --port=5001 --reload